### ISSUE TITLE
Doesn't work with python 3.7

### ISSUE THREAD

**Issue by souliane** [lucsorel/py2puml#17]
`pyproject.toml` says `python = "^3.7"`, but `ast.get_source_segment` has been introduced in python 3.8. It doesn't work with 3.7:

```
  File "/usr/local/lib/python3.7/dist-packages/py2puml/parsing/astvisitors.py", line 4, in <module>
    from ast import (
ImportError: cannot import name 'get_source_segment' from 'ast' (/usr/lib/python3.7/ast.py)
```

**Comment by lucsorel** [comment]
thank you @souliane for reporting this. I will update the toml file to specify that the library requires python 3.8+

**Comment by lucsorel** [comment]
release [0.5.2](https://github.com/lucsorel/py2puml/releases/tag/0.5.2) updated the documentation. Thank you again for reporting the need to update it.
